# Generated by Django 3.0.6 on 2020-05-09 17:51

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Todo Title', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Todo Description', null=True, verbose_name='Description')),
                ('completed', models.BooleanField(default=False)),
                ('due', models.DateTimeField(default=todo_app.models.days_from_now_1, help_text='Todo Due (default - 1 day from now)', verbose_name='due')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
